# Generated by Django 4.2.1 on 2023-06-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0003_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='basketline',
            constraint=models.UniqueConstraint(fields=('basket', 'product'), name='basket_product'),
        ),
    ]
