# Generated by Django 4.2.1 on 2023-06-06 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baskets', '0004_basketline_basket_product'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baskets.basket')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('card_number', models.CharField(max_length=16)),
                ('card_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=75)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('supplier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('Failed', 'Failed')], default='PENDING', max_length=25)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.customer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='orders.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.paymentmethod'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.shippingdetail'),
        ),
    ]
