# Generated by Django 4.2.1 on 2023-06-06 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.payment'),
        ),
    ]
